### PR TITLE
Fix percent column labels inconsistency

### PR DESCRIPTION
**Pull request by zeehio**
Thanks for this package. I find the labelling of column percentages inconsistent when the percentage is between 0.1 and 0.5%. 

Here is a reproducible example of the issue, with a plot. Please compare the `miss_0.2` label with the labels next to it:

``` r
library(visdat)
x <- data.frame(
  miss_0 = rep(1, 10000),
  miss_0.08 = c(rep(NA_real_, 8), rep(1, 10000-8)),
  miss_0.2 = c(rep(NA_real_, 20), rep(1, 10000-20)),
  miss_0.8 = c(rep(NA_real_, 80), rep(1, 10000-80)),
  miss_3.4 = c(rep(NA_real_, 340), rep(1, 10000-340)),
  miss_23 =  c(rep(NA_real_, 2300), rep(1, 10000-2300))
)
vis_miss(x, sort_miss = TRUE)
```

<sup>Created on 2023-02-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Before:**
- If the percentage is 0%, it shows as "0%".
- If the percentage is above 0.1%, round percentage to units (e.g 23.4% is "23%", 4.2% is "4%", "0.8%" is "1%")
- If the percentage  is below 0.1%, show "<0.1%"

**Issue:**
The behaviour of percentages between 0.1% and 0.5% is confusing. For instance, a percentage of "0.2%" appeared rounded to units, and was labelled as "0%", as if no missing values were found.

**Solution:**
- Percentages smaller than 0.1% are still displayed "<0.1%".
- Percentages smaller than 1% are displayed rounding to 0.1 (so "0.22%" would be "0.2%")
- Percentages larger than 1% are rounded to single percent units (so "23.456%" is "23%") like before

An alternative to this solution is to choose that percentages <1% become "<1%". That would also be a good solution. If you prefer that feel free to say so or just commit the change and merge at will.

With this pull request applied:

``` r
# remotes::install_github("zeehio/visdat@patch-1")
library(visdat)
x <- data.frame(
  miss_0 = rep(1, 10000),
  miss_0.08 = c(rep(NA_real_, 8), rep(1, 10000-8)),
  miss_0.2 = c(rep(NA_real_, 20), rep(1, 10000-20)),
  miss_0.8 = c(rep(NA_real_, 80), rep(1, 10000-80)),
  miss_3.4 = c(rep(NA_real_, 340), rep(1, 10000-340)),
  miss_23 =  c(rep(NA_real_, 2300), rep(1, 10000-2300))
)
vis_miss(x, sort_miss = TRUE)
```

<sup>Created on 2023-02-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by njtierney** [comment]
Hello!

This is a very lovely PR - thank you so much  for taking the time to detail it out as you have!

This catches a new bug, and I'm really grateful that you've caught it and also given a nice elegant solution 😄 

I can do these things if you would prefer (and am happy to!) but would you be able to add the following:

- Add a NEWS bullet for this change? 
- Add you example above as a new vdiffr test to capture and test this new behaviour

Thank you again!

**Comment by zeehio** [comment]
Thanks I will make those changes (and using "<1%" looks better than "0.3%" so I will change that as well).

It's been a busy week, I will try to get this done either today or next week.

Have a great weekend!

**Comment by zeehio** [comment]
Done. Feel free to merge :+1:

**Comment by njtierney** [comment]
Marvellous, thank you!

**Pull request merged**
